safe: false # This will enable custom plugins.
lsi: false
pygments: true
sass:
    style:  expanded  # nested|expanded|compact|compressed
    # "deploy_style:" is used only for building the site
    # (ie: not using the --watch flag)
    deploy_style: compressed  # nested|expanded|compact|compressed
    compile_in_place: false   # true|false